const katex = require('katex');

function cleanRedKaTeXErrors(html) {
    if (!html) return '';
    // Strip any katex-error red spans generated by KaTeX parse failures
    return html.replace(/<span class="katex-error"[^>]*>([\s\S]*?)<\/span>/g, (match, rawContent) => {
        // Strip LaTeX delimiters and backslashes from the raw content so it shows cleanly
        const cleanText = rawContent
            .replace(/\\text\{([^}]+)\}/g, '$1')
            .replace(/\\/g, '')
            .replace(/\$/g, '');
        return `<span class="clean-math">${cleanText}</span>`;
    });
}

function safeRenderKaTeX(expr, displayMode) {
    try {
        const rendered = katex.renderToString(expr.trim(), { displayMode, output: 'html', throwOnError: false });
        if (rendered.includes('katex-error') || rendered.includes('color:#cc0000')) {
            // If KaTeX generated a red error span, fall back to clean text
            const cleanExpr = expr
                .replace(/\\text\{([^}]+)\}/g, '$1')
                .replace(/\\/g, '');
            return `<span class="clean-math-inline">${cleanExpr}</span>`;
        }
        return rendered;
    } catch (e) {
        return `<span class="clean-math-inline">${expr}</span>`;
    }
}

const badKaTeXString1 = "A motorist travels a distance of $120km at an average speed of x km/h$ On the return journey, the speed is increased by $20km/h$";
const badKaTeXString2 = "A rectangular garden has a length of $(x+5) m' and a width of (x - 2)m$";

console.log('Testing Bad String 1:');
const expr1 = badKaTeXString1.match(/\$([^\$]+)\$/)[1];
const html1 = safeRenderKaTeX(expr1, false);
console.log('Has red error box?:', html1.includes('katex-error') || html1.includes('cc0000'));
console.log('HTML Output 1:', html1);

console.log('\nTesting Bad String 2:');
const expr2 = badKaTeXString2.match(/\$([^\$]+)\$/)[1];
const html2 = safeRenderKaTeX(expr2, false);
console.log('Has red error box?:', html2.includes('katex-error') || html2.includes('cc0000'));
console.log('HTML Output 2:', html2);
